---
version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/ati/IR-SZVK-08/nginx_config:/config
      - /home/ati/IR-SZVK-08/webroot:/webroot
    ports:
      - 80:8080
    restart: unless-stopped
    
